import { colors as c } from 'spencer-color'

export default {
  atlantic: [
    { short: 'BOS', place: 'Boston', name: 'Boston Bruins', color: c.brown },
    { short: 'BUF', place: 'Buffalo', name: 'Buffalo Sabres', color: c.sea },
    { short: 'DET', place: 'Detroit', name: 'Detroit Red Wings', color: c.red },
    {
      short: 'FLR',
      place: 'Florida',
      name: 'Florida Panthers',
      color: c.cherry,
    },
    {
      short: 'MTL',
      place: 'Montreal',
      name: 'Montreal Canadiens',
      color: c.rouge,
    },
    { short: 'OTT', place: 'Ottawa', name: 'Ottawa Senators', color: c.cherry },
    {
      short: 'TMP',
      place: 'Tampa',
      name: 'Tampa Bay Lightning',
      color: c.royal,
    },
    {
      short: 'TOR',
      place: 'Toronto',
      name: 'Toronto Maple Leafs',
      color: c.blue,
    },
  ],
  metro: [
    {
      short: 'CAR',
      place: 'Carolina',
      name: 'Carolina Hurricanes',
      color: c.fire,
    },
    {
      short: 'COL',
      place: 'Columbus',
      name: 'Columbus Blue Jackets',
      color: c.navy,
    },
    {
      short: 'NJ',
      place: 'New Jersey',
      name: 'New Jersey Devils',
      color: c.burnt,
    },
    {
      short: 'NYI',
      place: 'Long Island',
      name: 'New York Islanders',
      color: c.orange,
    },
    {
      short: 'NYR',
      place: 'New York',
      name: 'New York Rangers',
      color: c.rouge,
    },
    {
      short: 'PHL',
      place: 'Philadelphia',
      name: 'Philadelphia Flyers',
      color: c.orange,
    },
    {
      short: 'PIT',
      place: 'Pittsburgh',
      name: 'Pittsburgh Penguins',
      color: c.fudge,
    },
    {
      short: 'WSH',
      place: 'Washington',
      name: 'Washington Capitals',
      color: c.cherry,
    },
  ],
  central: [
    { short: 'ARI', place: 'Arizona', name: 'Arizona Coyotes', color: c.rouge },
    {
      short: 'CHI',
      place: 'Chicago',
      name: 'Chicago Blackhawks',
      color: c.fudge,
    },
    {
      short: 'COL',
      place: 'Colorado',
      name: 'Colorado Avalanche',
      color: c.burnt,
    },
    { short: 'DAL', place: 'Dallas', name: 'Dallas Stars', color: c.olive },
    {
      short: 'MIN',
      place: 'Minnesota',
      name: 'Minnesota Wild',
      color: c.green,
    },
    {
      short: 'NSH',
      place: 'Nashville',
      name: 'Nashville Predators',
      color: '#b2b17b',
    },
    { short: 'WIN', place: 'Winnipeg', name: 'Winnipeg Jets', color: c.sea },
  ],
  pacific: [
    { short: 'ANA', place: 'Anaheim', name: 'Anaheim Ducks', color: c.dimgrey },
    { short: 'CAL', place: 'Calgary', name: 'Calgary Flames', color: c.red },
    {
      short: 'EDM',
      place: 'Edmonton',
      name: 'Edmonton Oilers',
      color: c.orange,
    },
    {
      short: 'LOS',
      place: 'Los Angeles',
      name: 'Los Angeles Kings',
      color: c.black,
    },
    { short: 'SJ', place: 'San Jose', name: 'San Jose Sharks', color: c.sky },
    {
      short: 'VAN',
      place: 'Vancouver',
      name: 'Vancouver Canucks',
      color: c.blue,
    },
    {
      short: 'VGS',
      place: 'Vegas',
      name: 'Vegas Golden Knights',
      color: '#b2b17b',
    },
    {
      short: 'STL',
      place: 'Seattle',
      name: 'Seattle Kraken',
      color: c.greygreen,
    },
  ],
  //defunct
  // 'California Golden Seals': c.green,
  // 'Kansas City Scouts': c.navy,
  // 'Cleveland Barons': c.red,
  // 'Atlanta Flames': c.orange,
  // 'Colorado Rockies': c.navy,
  // 'Minnesota North Stars': c.olive,
  // 'Quebec Nordiques': c.sky,
  // 'Winnipeg_Jets_(1972–96)': c.rouge,
  // 'Hartford Whalers': c.green,
  // 'Atlanta Thrashers': c.fire,
}
